{"name": "test_1", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 3", "trace": "self = <testcase.test_calc.TestA object at 0x11068fe80>\n\n    def test_1(self):\n>       assert 1 == 3\nE       assert 1 == 3\n\ntest_calc.py:35: AssertionError"}, "attachments": [{"name": "log", "source": "ea86b822-59fa-405e-a2d6-214010cd49d3-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "2d07f36b-7f91-4160-849f-57750cf61455-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "df3b607c-6e17-4835-bd23-f1d73fbe265a-attachment.txt", "type": "text/plain"}], "start": 1564493501525, "stop": 1564493501526, "uuid": "3b5ac747-c4b1-41cb-a359-f012e241af82", "historyId": "327fcfb14cbdb3f25509b479cccf419d", "fullName": "test_calc.TestA#test_1", "labels": [{"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestA"}, {"name": "host", "value": "anxiaodongdeMacBook-Pro.local"}, {"name": "thread", "value": "84097-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc"}]}