{"name": "test_four", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 8", "trace": "@pytest.mark.run(order=1)\n    def test_four():\n>       assert 3==8\nE       assert 3 == 8\n\ntest_demo.py:22: AssertionError"}, "attachments": [{"name": "log", "source": "c9b5bea5-e28a-46c0-90aa-6bf8f1af635f-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "e888fa15-e81d-42b6-af91-6df8138eed1f-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "504df14b-13fb-42bd-b20d-b545e50ec78c-attachment.txt", "type": "text/plain"}], "start": 1564493501587, "stop": 1564493501587, "uuid": "9d7c045b-6126-4c88-80cf-4a59458d496d", "historyId": "69e658f4c2ed6c6456389aaffd2e911c", "fullName": "test_demo#test_four", "labels": [{"name": "suite", "value": "test_demo"}, {"name": "host", "value": "anxiaodongdeMacBook-Pro.local"}, {"name": "thread", "value": "84097-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_demo"}]}